### ISSUE TITLE
Growatt doesn't update anymore

### ISSUE THREAD

**Issue by ntpckr** [sincze/Domoticz#12]
Since yesterday (12 October 2022) the generated and current power is not updated anymore. There's no error shown when running the script from terminal.

**Comment by sincze** [comment]
That's interesting indeed. Can you manually remove your cookie please. (location is mentioned in the script).

My monitor shows data (it is pretty cloudy today so not that much).
![image](https://user-images.githubusercontent.com/5776333/195562013-4c269d5b-ae96-426e-83ec-2b0067dd0012.png)

**Comment by ntpckr** [comment]
sorry... my mistake... configured a device that is not allowed to communicate with internet and placed in the group of smart home devices. when I did that, the rule was for all the devices set and not only for that one device...
