### ISSUE TITLE
I get a 502 error message

### ISSUE THREAD

**Issue by fbosman** [sincze/Domoticz#2]
I do not get any info from the Growatt API, when debugging the return is 502.
My credentials are ok..

**Comment by sincze** [comment]
Did you switch on all debugging so we can see if you obtain a token correctly?
502 would indicate some sort of server problem. As the Growatt installation that I monitor is working this seems unlikely and needs some more investigation indeed.

**Comment by fbosman** [comment]
I did find the issue.  The password MD5 is not correct in a standard md5 calculation.
I found a python script:
    Normal MD5, except add c if a byte of the digest is less than 10.
    """
    password_md5 = hashlib.md5(password.encode("utf-8")).hexdigest()
    for i in range(0, len(password_md5), 2):
        if password_md5[i] == "0":
            password_md5 = password_md5[0:i] + "c" + password_md5[i + 1 :]
    return password_md5
Can you merge this in your code?

**Comment by sincze** [comment]
Great find, however I am not a programmer and use the MD5 calculation as provided by PHP.

[PHP Manual](https://www.php.net/manual/en/function.md5.php)
[W3Schools](https://www.w3schools.com/php/func_string_md5.asp)
Can you rewrite it to PHP and make a pull request?

I assume the answer is just, but just in case.
Did you test your generated python password in the PHP script? Line 50? 

`define('PASSWORD', '*****');`

And then it works?

Small alternative would be to change your password for the website, 
and the MD5 calculation should do it's job.

**Comment by sincze** [comment]
Fixed with merge Request. tnx.
