### ISSUE TITLE
Issue while executing installing

### ISSUE THREAD

**Issue by hendrikenrenny** [sincze/Domoticz#4]
Hi,

When installign teh Growatt php script, executing "sudo apt-get install php7.0 php7.0-curl php7.0-gd php7.0-imap php7.0-json php7.0-mcrypt php7.0- php7.0-cli" I get all kinds of errors. See below. Any idea how to overcome this?

I've installed the latest Rasbian and Domoticz (stable) versions.

Pls let me know!

H.

QUOTE

pi@raspberrypi:~ $ sudo apt-get install php7.0 php7.0-curl php7.0-gd php7.0-imap php7.0-json php7.0-mcrypt php7.0- php7.0-cli
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'php7.0-thrift' for regex 'php7.0'
Note, selecting 'php7.0-remctl' for regex 'php7.0'
Note, selecting 'php7.0-common' for regex 'php7.0'
Note, selecting 'php7.0-curl' for regex 'php7.0'
Note, selecting 'php-remctl' instead of 'php7.0-remctl'
Note, selecting 'php7.0-thrift' for regex 'php7.0'
Note, selecting 'php7.0-remctl' for regex 'php7.0'
Note, selecting 'php7.0-common' for regex 'php7.0'
Note, selecting 'php7.0-curl' for regex 'php7.0'
Package 'php7.0-common' is not installed, so not removed
Note, selecting 'php-remctl' instead of 'php7.0-remctl'
Package 'php7.0-thrift' is not installed, so not removed
Package 'php7.0-curl' is not installed, so not removed
Package php7.0-curl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php7.0-curl' has no installation candidate
E: Unable to locate package php7.0-gd
E: Couldn't find any package by glob 'php7.0-gd'
E: Couldn't find any package by regex 'php7.0-gd'
E: Unable to locate package php7.0-imap
E: Couldn't find any package by glob 'php7.0-imap'
E: Couldn't find any package by regex 'php7.0-imap'
E: Unable to locate package php7.0-json
E: Couldn't find any package by glob 'php7.0-json'
E: Couldn't find any package by regex 'php7.0-json'
E: Unable to locate package php7.0-mcrypt
E: Couldn't find any package by glob 'php7.0-mcrypt'
E: Couldn't find any package by regex 'php7.0-mcrypt'
E: Unable to locate package php7.0-cli
E: Couldn't find any package by glob 'php7.0-cli'
E: Couldn't find any package by regex 'php7.0-cli'
pi@raspberrypi:~ $ ^C
pi@raspberrypi:~ $ sudo apt-get install php7.0 php7.0-curl php7.0-gd php7.0-imap php7.0-json php7.0-mcrypt php7.0- php7.0-cli
Note, selecting 'php7.0-common' for regex 'php7.0'
Note, selecting 'php7.0-curl' for regex 'php7.0'
Note, selecting 'php-remctl' instead of 'php7.0-remctl'
Note, selecting 'php7.0-thrift' for regex 'php7.0'
Note, selecting 'php7.0-remctl' for regex 'php7.0'
Note, selecting 'php7.0-common' for regex 'php7.0'
Note, selecting 'php7.0-curl' for regex 'php7.0'
Package 'php7.0-common' is not installed, so not removed
Note, selecting 'php-remctl' instead of 'php7.0-remctl'
Package 'php7.0-thrift' is not installed, so not removed
Package 'php7.0-curl' is not installed, so not removed
Package php7.0-curl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php7.0-curl' has no installation candidate
E: Unable to locate package php7.0-gd
E: Couldn't find any package by glob 'php7.0-gd'
E: Couldn't find any package by regex 'php7.0-gd'
E: Unable to locate package php7.0-imap
E: Couldn't find any package by glob 'php7.0-imap'
E: Couldn't find any package by regex 'php7.0-imap'
E: Unable to locate package php7.0-json
E: Couldn't find any package by glob 'php7.0-json'
E: Couldn't find any package by regex 'php7.0-json'
E: Unable to locate package php7.0-mcrypt
E: Couldn't find any package by glob 'php7.0-mcrypt'
E: Couldn't find any package by regex 'php7.0-mcrypt'
E: Unable to locate package php7.0-cli
E: Couldn't find any package by glob 'php7.0-cli'
Reading package lists... Doneby regex 'php7.0-cli'
Building dependency tree
Reading state information... Done
Note, selecting 'php7.0-thrift' for regex 'php7.0'
Note, selecting 'php7.0-remctl' for regex 'php7.0'
Note, selecting 'php7.0-common' for regex 'php7.0'
Note, selecting 'php7.0-curl' for regex 'php7.0'
Note, selecting 'php-remctl' instead of 'php7.0-remctl'
Note, selecting 'php7.0-thrift' for regex 'php7.0'
Note, selecting 'php7.0-remctl' for regex 'php7.0'
Note, selecting 'php7.0-common' for regex 'php7.0'
Note, selecting 'php7.0-curl' for regex 'php7.0'
Package 'php7.0-common' is not installed, so not removed
Note, selecting 'php-remctl' instead of 'php7.0-remctl'
Package 'php7.0-thrift' is not installed, so not removed
Package 'php7.0-curl' is not installed, so not removed
Package php7.0-curl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php7.0-curl' has no installation candidate
E: Unable to locate package php7.0-gd
E: Couldn't find any package by glob 'php7.0-gd'
E: Couldn't find any package by regex 'php7.0-gd'
E: Unable to locate package php7.0-imap
E: Couldn't find any package by glob 'php7.0-imap'
E: Couldn't find any package by regex 'php7.0-imap'
E: Unable to locate package php7.0-json
E: Couldn't find any package by glob 'php7.0-json'
E: Couldn't find any package by regex 'php7.0-json'
E: Unable to locate package php7.0-mcrypt
E: Couldn't find any package by glob 'php7.0-mcrypt'
E: Couldn't find any package by regex 'php7.0-mcrypt'
E: Unable to locate package php7.0-cli
E: Couldn't find any package by glob 'php7.0-cli'
E: Couldn't find any package by regex 'php7.0-cli'

UNQUOTE

**Comment by sincze** [comment]
Let me check

`pi@raspberrypi:~ $ sudo apt-get install php7.0 php7.0-curl php7.0-gd php7.0-imap php7.0-json php7.0-mcrypt php7.0- php7.0-cli
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'php7.0' is not installed, so not removed
The following additional packages will be installed:
  apache2 apache2-bin apache2-data apache2-utils fontconfig-config fonts-dejavu-core libapache2-mod-php7.0 libapr1 libaprutil1 libaprutil1-dbd-sqlite3
  libaprutil1-ldap libc-client2007e libfontconfig1 libgd3 libjbig0 libltdl7 liblua5.2-0 libmcrypt4 libtiff5 libwebp6 libxpm4 mlock php-common php7.0-common
  php7.0-opcache php7.0-readline ssl-cert
Suggested packages:
  www-browser apache2-doc apache2-suexec-pristine | apache2-suexec-custom php-pear uw-mailutils libgd-tools libmcrypt-dev mcrypt openssl-blacklist
The following NEW packages will be installed:
  apache2 apache2-bin apache2-data apache2-utils fontconfig-config fonts-dejavu-core libapache2-mod-php7.0 libapr1 libaprutil1 libaprutil1-dbd-sqlite3
  libaprutil1-ldap libc-client2007e libfontconfig1 libgd3 libjbig0 libltdl7 liblua5.2-0 libmcrypt4 libtiff5 libwebp6 libxpm4 mlock php-common php7.0
  php7.0-cli php7.0-common php7.0-curl php7.0-gd php7.0-imap php7.0-json php7.0-mcrypt php7.0-opcache php7.0-readline ssl-cert
The following held packages will be changed:
  php7.0
0 upgraded, 34 newly installed, 0 to remove and 0 not upgraded.
Need to get 8,053 kB of archives.
After this operation, 25.1 MB of additional disk space will be used.
Do you want to continue? [Y/n]`

**Comment by hendrikenrenny** [comment]
Hi,

Inspired by your answer, I used the command:

sudo apt-get install php7.3 php7.3-curl php7.3-gd php7.3-imap php7.3-json php7.3- php7.3-cli

and got it working.

I did install the plugin, however, domoticz becomes very unstable and stops even. Don't know why. Domoticz logs don't give a clear picture.

Thanks for your help again!

H.

**Comment by hendrikenrenny** [comment]
Hi Sincze,

I tested the plugin on my "test RPI" with the latest beta version of domoticz (4.11290), and it works like a charm. For some reason, the last stable version 4.10717 can't cope with the plugin.

I will install it on my main domoticz RPI as soon as the next stable version is released. I assume it will work then properly.

Thanks for all your good work! Really appreciated!

H.

**Comment by sincze** [comment]
PHP install issue was fixed by user @hendrikenrenny .
Plugin not suitable for stable Domoticz stable version 4.10717 , this is mentioned in the pre-reqs.
