### ISSUE TITLE
Keeps reporting total as the daily amount

### ISSUE THREAD

**Issue by pbc278** [sincze/Domoticz#6]
I'm running the script for over a week now and the first few days it was reporting the total amount in the daily graph. then it was good for a few days, reporting the daily amount of power from Growatt portal in the daily graph, but now it is reporting the total amount again on the daily graph. See attached image

![Growatt_domoticz](https://user-images.githubusercontent.com/60828427/104650349-5846be80-56b6-11eb-9e9a-56933463abcd.PNG)

I hope there is (or will be) a fix and something to undo the 'damage' in the data...

Kind regards,
BC

**Comment by sincze** [comment]
Hi. It seems different users are not experience issues with the current version, can you check?? 
I will close the issue for now.
